SAMPLE_LIST = [
    'Shipper',
    'Shipper Address',
    'Consignee Name',
    'Consignee Address',
    'Vessel/Voyage',
    'Actual Voyage Number',
    'Vessel Flag',
    'Master B/L or Master Bill of Lading',
    'Bill Of Lading',
    'Port of Origin',
    'Port of Loading',
    'Port of Destination',
    'Last Departure Port',
    'Berth',
    'Manifest/Registration #',
    'Office of Submission or Wharfinger',
    'Container',
    'Weight',
    'Measure',
    'Package or Piece Count',
    'Commodity',
    'Marks'
]
